<?php

namespace app\v1\controller;

use think\Controller;
use think\Request;
class  AdminBase extends Controller
{
   protected  $post = '';

   protected  $get  = '';

   protected  $ajax = '';


   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       $this->post = Request::instance()->isPost();
       $this->get = Request::instance()->isGet();
       $this->ajax = Request::instance()->isAjax();
   }



}